#pragma once

#include <string>
#include <unordered_map>
#include <unordered_set>

// Doom class information auto-generated from ZDoom wiki.
// Generated by scripts/fetch_doom_classes.py

// All Doom classes as a set of strings
extern std::unordered_set<std::string> allDoomClasses;

// Mapping from category names to sets of class names
extern std::unordered_map<std::string, std::unordered_set<std::string>> categoryToClasses;

// Mapping from class names to their category
extern std::unordered_map<std::string, std::string> classToCategory;
